- type: job
  id: Quartermaster
  name: job-name-qm
  startingGear: QuartermasterGear
  departments:
  - Cargo
  icon: "QuarterMaster"
  supervisors: job-supervisors-hop
  access:
  - Cargo
  - Maintenance
  - External

- type: startingGear
  id: QuartermasterGear
  equipment:
    head: ClothingHeadHatCargosoft
    jumpsuit: ClothingUniformJumpsuitQM
    back: ClothingBackpackFilled
    shoes: ClothingShoesColorBrown
    id: QuartermasterPDA
    ears: ClothingHeadsetCargo
  innerclothingskirt: ClothingUniformJumpskirtQM
  satchel: ClothingBackpackSatchelFilled
  duffelbag: ClothingBackpackDuffelFilled
