- type: startingGear
  id: FugitiveStartingGear
  equipment:
    jumpsuit: ClothingUniformJumpsuitPrisoner
    gloves: ClothingHandsGlovesColorYellowBudget
    back: ClothingBackpack
    shoes: ClothingShoesColorBlack
  innerclothingskirt: ClothingUniformJumpsuitPrisoner
  inhand:
    right hand: ToolboxElectricalFilled
